### ISSUE TITLE
How to do image object segmentation on the pre-trained model?

### ISSUE THREAD

**Issue by hqsiswiliam** [facebookresearch/dino#103]
Hi there,

Thanks for the great work. Since there is a script for video object segmentation, I'd like to ask if there is any script for the image object segmentation?

**Comment by mathildecaron31** [comment]
Hi,

thanks for your interest in this work. Is https://github.com/facebookresearch/dino/blob/main/visualize_attention.py what you are looking for ?

**Comment by hqsiswiliam** [comment]
Hi @mathildecaron31 , thanks for your response. Not the attention visualization actually. After pre-training, I have a bunch of labelled image segmentation data. I would like to further fine-tune using the labelled data. I wonder how I can do the fine-tuning?

**Comment by mathildecaron31** [comment]
Hi @hqsiswiliam 

I think you can take a look at the "deit" baseline used in Table 2.b) of the swin transformer paper: https://arxiv.org/pdf/2103.14030.pdf

They use "deit-S" (aka ViT-S) architecture for segmentation.

![image](https://user-images.githubusercontent.com/20599397/129933575-005ed315-a9e3-4101-9c29-0755b70eeb10.png)

**Comment by hqsiswiliam** [comment]
Thank you so much. This would be very helpful for me.
