### ISSUE TITLE
Can the  DINO ImageNet-21K Pretrained model will be published?

### ISSUE THREAD

**Issue by CauchyFood** [facebookresearch/dino#105]
Hi, @mathildecaron31, thanks for your great work,

I wonder hat is there is any report or models on ImageNet-21K datasets?

Thanks a lot!

**Comment by mathildecaron31** [comment]
Hi @CauchyFood 
Thanks a lot for your kind words. Unfortunately I have not trained any models on ImageNet21k dataset.

**Comment by CauchyFood** [comment]
Thank you!
