### ISSUE TITLE
Python environment setup?

### ISSUE THREAD

**Issue by gordicaleksa** [facebookresearch/dino#107]
Quick question regarding how you folks at Facebook are building Python environments?

Currently it seems like I have to manually investigate the packages used in particular Python files and download a certain version of the package manually - which may lead to people having dependency problems, or am I missing something out here?

**Comment by mathildecaron31** [comment]
Hi @gordicaleksa, I typically use conda environments (anaconda3/5.0.1).

**Comment by gordicaleksa** [comment]
Got it, thanks! Me too - I meant more do you use environment.yml/requirements.txt or other ways to automate the installation of all Python packages?

**Comment by mathildecaron31** [comment]
Mmm yes I see, I could have created a file like this to make replicating my environment easier...
The thing is I don't want to share my environment in its current status because there's a lot of stuff in it which are not relevant to this project

**Comment by SuroshAhmadZobair** [comment]
Hi 
This is such a great Repo. It would be a pity not to have environment.yml/requirements.txt !
@gordicaleksa It would be a huge time saver.  Would you mind sharing your environment?

Thanks in advance!

**Comment by SuroshAhmadZobair** [comment]
Hi!
Never mind. I used detectron2's environment and it works fine. 
Cheers!
