### ISSUE TITLE
License of weights

### ISSUE THREAD

**Issue by DavHoffmann** [facebookresearch/dino#108]
Hi,

first of all, thanks for the nice repository. I was wondering what is the license of the pretrained weights? Does the Apache 2.0 license cover them as well, or are they published under a different license?

**Comment by mathildecaron31** [comment]
Hi @DavHoffmann 

Thanks for your kind words. Yes I believe the license covers the weights as well.

**Comment by DavHoffmann** [comment]
Great! 
Thanks for the fast reply.
