### ISSUE TITLE
Should width, height be reversed?

### ISSUE THREAD

**Issue by NielsRogge** [facebookresearch/dino#111]
I see [here](https://github.com/facebookresearch/dino/blob/de9ee3df6cf39fac952ab558447af1fa1365362a/vision_transformer.py#L197), that the pixel values that are forwarded through the Transformer encoder are assumed to be of shape `(batch_size, num_channels, width, height)`. However, is it possible that height and width should be reversed (as, according to torchvision's [documentation](https://pytorch.org/vision/stable/transforms.html), a batch of PyTorch tensors is assumed to be of shape `(B, C, H, W)`? 

Of course, if training on square images, height and width are equal, hence there's no impact.

**Comment by mathildecaron31** [comment]
Hello @NielsRogge 

Sorry for the confusion, it is just that as a non-native english speaker I am consistently confused with height and width... And as you say it works regardless because we deal with square images.

**Comment by woctezuma** [comment]
Don't worry, it is confusing for everyone, regardless of being a native speaker! 🫂
