### ISSUE TITLE
returned non-zero exit status 1

### ISSUE THREAD

**Issue by Harry-KIT** [facebookresearch/dino#113]
subprocess.CalledProcessError: Command '['/home/gayrat/anaconda3/envs/Dino/bin/python', '-u', 'main_dino.py', '--local_rank=4', '--arch', 'vit_small', '--data_path', './dataset/resized_img', '--output_dir', './results']' returned non-zero exit status 1

**Comment by mathildecaron31** [comment]
Hi @Harry-KIT 

Have you been able to fix the issue ? If yes can you close the issue ? otherwise how can I help ?

**Comment by Harry-KIT** [comment]
Yes i solved. Thank you
    On Friday, September 17, 2021, 07:05:25 PM GMT+9, Couffou ***@***.***> wrote:  
 
 


Hi @Harry-KIT

Have you been able to fix the issue ? If yes can you close the issue ? otherwise how can I help ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by woctezuma** [comment]
I think you can close the issue as it is not an issue with `dino` itself.
