### ISSUE TITLE
thresholded sorted attention is ignored in video_generation

### ISSUE THREAD

**Issue by xvdp** [facebookresearch/dino#118]
`th_attn=` is computed in video_generation.py, lines 198-215 but not used or output by the _inference function.  The 60% mass threshold appears to be ignored in the output and reprocessing the dog video it is clear that the segmentation mask does not use this threshold.
I am not sure what this means, but considering that thresholding is mentioned in the paper several times, I would be curious what to do with th_attn
thank you

**Comment by woctezuma** [comment]
If it is as for image, then it could be used for visualization.

https://github.com/facebookresearch/dino/blob/94175993abde84179449d79e22eab7ea28dec14b/visualize_attention.py#L213

**Comment by xvdp** [comment]
thank you
