### ISSUE TITLE
Cannot reproduce kNN and linear evaluation result of ViT-small trained without multi-crop.

### ISSUE THREAD

**Issue by YiF-Zhang** [facebookresearch/dino#122]
Hi, thanks for the excellent work! I have been running several experiments to reproduce the ViT-small results **without** multi-crop, i.e. kNN results claimed in Table 9 (59.9), and linear evaluation results claimed in Table 8 (67.8). I believe my settings as follows are identical to your instructions in paper and in this repo: 
```
python -m torch.distributed.launch --nproc_per_node=8 main_dino.py --arch vit_small --data_path /my/path --output_dir /my/output --global_crops_scale 0.14 1.0
```
It was trained on a two 8-GPU machine. And I changed `global_crops_scale` as suggested in the code. However my kNN result is 58.28, my linear evaluation results is 64.16 (the log is provided [here](https://gist.github.com/YiF-Zhang/eae4d277ae805ec2885825729c91bc47)).

So maybe you guys can provide some suggestions of reproducing your results **without** multi-crop? (the results **with** multi-crop are solid) Or is there something missing in my settings?

**Comment by mathildecaron31** [comment]
Hi @YiF-Zhang 
Thanks for your interest in this work. Let me share my config for the run without multi-crop:

arch: vit_small
batch_size_per_gpu: 64
clip_grad: 0
epochs: 300
freeze_last_layer: 1
global_crops_scale: [0.14, 1.0]
local_crops_number: 0
lr: 0.0005
min_lr: 1e-05
momentum_teacher: 0.996
use_bn_in_head: False
norm_last_layer: False
optimizer: adamw
out_dim: 65536
patch_size: 16
teacher_temp: 0.07
use_fp16: True
warmup_epochs: 10
warmup_teacher_temp: 0.04
warmup_teacher_temp_epochs: 30
weight_decay: 0.04
weight_decay_end: 0.4
world_size: 16


I think the main argument you're missing is `--norm_last_layer false`
Hope that helps

**Comment by mathildecaron31** [comment]
I can also share the checkpoint and logs if that helps.

**Comment by YiF-Zhang** [comment]
Hi @mathildecaron31 thanks a lot for the reply! Indeed setting `norm_last_layer` to `False` improves performance. I found tuning teacher temperature also improves performance (without multi-crop). Setting
```
... --teacher_temp 0.07 --warmup_teacher_temp_epochs 30
```
yield 60.57 on kNN evaluation. Setting
```
... --teacher_temp 0.07 --warmup_teacher_temp_epochs 30 --norm_last_layer False
```
yield 61.28 on kNN evaluation.
