### ISSUE TITLE
ImageNet Linear weights for ViT-B/8?

### ISSUE THREAD

**Issue by lucasb-eyer** [facebookresearch/dino#129]
Hi, in the README, you provide this model:

![image](https://user-images.githubusercontent.com/1476029/134524655-cbcc6e15-c0f9-42c7-afa2-47679ffef225.png)

however, further down where we can find the linear heads for ImageNet classification, the head for that model is missing:

![image](https://user-images.githubusercontent.com/1476029/134524861-0434c11c-095c-45e9-b89e-7cd1740ac06a.png)

in case you still have them lying around, would you mind uploading those too?

Thanks!

**Comment by mathildecaron31** [comment]
Hi @lucasb-eyer, good catch, I'll take a look and try to update them shortly!

**Comment by mathildecaron31** [comment]
https://github.com/facebookresearch/dino/commit/d2f3156bb34c32ae54312de7fe4e31580f12ff7f

**Comment by lucasb-eyer** [comment]
whew that was quick, merci beaucoup!
