### ISSUE TITLE
Rationale behind DeiT-S/8 being better than ViT-B/8 at k-NN?

### ISSUE THREAD

**Issue by woctezuma** [facebookresearch/dino#13]
Here is a quote from this comment https://github.com/facebookresearch/dino/issues/8#issuecomment-830846130:

> As a matter of fact, on copy detection datasets, I've found the base models to perform clearly better than the small ones: I get better performance with Base16x16 than with Small8x8 though Small8x8 is better at k-NN ImNet.

I assume this is about Table 2 from the article.

![Table 2](https://i.imgur.com/ApGkaqN.png)

We see that for **both** of the tasks (Linear and k-NN):
- DeiT-S/16 is **worse** than ViT-B/16,
- the /8 architectures are **better** than the /16 architectures.

However, when it comes to comparing the /8 architectures:
- DeiT-S/8 is **worse** than ViT-B/8 at the Linear task, as expected,
- DeiT-S/8 is **better** than ViT-B/8 at the k-NN task, which is intriguing.

What is the rationale behind DeiT-S/8 being better than ViT-B/8 at the k-NN ImNet task?

**Comment by woctezuma** [comment]
Also, you mention that you get better results with ViT-B/16 than with DeiT-S/8 for copy detection, which is interesting because it means that a /16 architecture can perform better than a /8 architecture. Basically, from table 4 and your comment, the results are better with ViT-B/8 than with ViT-B/16, which in turn are better than with DeiT-S/8 for copy detection.

[Table 4](https://i.imgur.com/r8nj2Vr.png)

What about image retrieval (cf. Table 3 below)? How does DeiT-S/8 compare to ViT-B/16 and ViT-B/8?

![Table 3](https://i.imgur.com/d8e01bu.png)

**Comment by mathildecaron31** [comment]
Hi @woctezuma 

I think it is difficult to determine beforehand which architecture will perform the best. I would recommend trying our pretrained networks, benchmark the performance with these and choose according to that.

> What is the rationale behind DeiT-S/8 being better than ViT-B/8 at the k-NN ImNet task?

Regarding ViT-B/8 vs DeiT-S/8, in my opinion the difference in performance is simply explained by the quantity of respective runs that I did with them. In other words, my belief is that with more experiments, it should be possible to push the performance of ViT-B/8 more. DeiT-S is very light/fast to experiment with, and I basically chose all my hyperparameters based on the performance with this model (as you can see in the ablations in our paper). On the other hand, I performed only 2 runs with ViT-B/8, and these runs were only for 300 epochs (while DeiT-S are trained for 800 epochs)!

Hope that helps.

**Comment by woctezuma** [comment]
Thank you, it helps put things in perspective! :)

**Comment by woctezuma** [comment]
I come back here to say that I am pretty impressed with the results when it comes to image similarity.

Here is an example:

![Truck](https://i.imgur.com/WXh93No.png)

**Comment by woctezuma** [comment]
To summarize the observations:
- for the Linear task: `ViT-S/16` < `ViT-B/16`< **`ViT-S/8`** < `ViT-B/8`
- for the k-NN task: `ViT-S/16` < `ViT-B/16` < `ViT-B/8` < **`ViT-S/8`**
- for the copy-detection task: `ViT-S/16` < **`ViT-S/8`** < `ViT-B/16` < `ViT-B/8`
