### ISSUE TITLE
Restart from checkpoint

### ISSUE THREAD

**Issue by hllowold** [facebookresearch/dino#132]
I followed the implementation and used submitit to run the training script:
The train script:
python run_with_submitit.py --nodes 2 --ngpus 2 --arch vit_small --data_path /home/data/imagenette2-320/train --output_dir /home/checkpoint/experiments

Following files were created in the output_dir: 
1720828_submitted.pkl, 1720828_submission.sh, 1720828_1_log.err, 1720828_1_log.out,1720828_0_log.out, 89a92d2d34884f639f4486949718b337_init, 1720828_0_log.err
I could not find the checkpoints (.pth files), unless I am missing something.

Secondly, can you please advice me how to restart the script from the checkpoint

Thanks

**Comment by mathildecaron31** [comment]
Hi @hllowold, a checkpoint should be written in the output_dir after each epoch. Are you sure your job has run until the completion of an entire epoch ? I'd suspect that it crashed for some reason before the end of the epoch and that is why you are not seeing the checkpoint.
