### ISSUE TITLE
Because a simple concat would be too easy!

### ISSUE THREAD

**Issue by lucasb-eyer** [facebookresearch/dino#134]
https://github.com/facebookresearch/dino/blob/d2f3156bb34c32ae54312de7fe4e31580f12ff7f/eval_linear.py#L211-L212

whyyyyyy :rofl: 

I'm poking fun, so feel free to ignore me and just close the issue, but am also wondering if there's a genuine reason to do this, or it's just "eh, this happened, whatever"?

(if it's not clear, a simple concat would do `abc + def = abcdef`, while this results in `adbecf`. It won't change any results, but it matters to me because I'm loading the DINO weights into a jax codebase.)

**Comment by mathildecaron31** [comment]
eh, this happened, whatever :p

**Comment by mathildecaron31** [comment]
More seriously, it comes from a former version of my code. I had changed to a much more simple concat in the public release but I realized when you opened the other issue on ViT-B/8 linear weights that the linear weights were as a result not compatible with the "abcdef" format.

I could then either manually modify the linear weights or modify the linear eval code accordingly and I lazily chose the second option...

See https://github.com/facebookresearch/dino/commit/d2f3156bb34c32ae54312de7fe4e31580f12ff7f
![image](https://user-images.githubusercontent.com/20599397/135047994-6df96c78-ad11-46fe-9d96-cae418d19878.png)

**Comment by lucasb-eyer** [comment]
oh, in this case I'm very glad that you realized it when adding the weight, because I may have never figured this out!

In any case, this was fun :) Thanks for your support, I rate 10/10!
