### ISSUE TITLE
eval_knn.py with --use_cuda False

### ISSUE THREAD

**Issue by mgpadalkar** [facebookresearch/dino#135]
Noticed a minor problem in eval_knn.py with `--use_cuda False` for handing out of memory error.
It stops with the error:
```
  File "eval_knn.py", line 164, in knn_classifier
    retrieval_one_hot.scatter_(1, retrieved_neighbors.view(-1, 1), 1)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

It occurs because of the following line https://github.com/facebookresearch/dino/blob/9bebc3fe8e4d359d3f1408eeb7798905ad56ef28/eval_knn.py#L148-L148

Changing this to
```
retrieval_one_hot = torch.zeros(k, num_classes).to(train_features.device)
```
solves the problem irrespective of `--use_cuda`.

**Comment by mathildecaron31** [comment]
Hi @mgpadalkar 
Good catch, can you send a PR ?

**Comment by mgpadalkar** [comment]
Hi @mathildecaron31,
Sure, will do it right away! Thanks :-)
