### ISSUE TITLE
Onnx pretrained

### ISSUE THREAD

**Issue by Armin234** [facebookresearch/dino#14]
Your work looks very interesting.
 I'm not familiar with Pytorch / Python and it would be great if the pre-trained nets could be provided in ONNX format.

Regards Armin

**Comment by xhlulu** [comment]
I'm not familiar with ONNX, but I heard it's pretty well supported by Pytorch. Have you tried following [this tutorial](https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html)?

**Comment by Armin234** [comment]
no, i haven't tried the tutorial. I'm not enthusiastic about installlingg python etc. and learning to use them only to be able to makeg some inference and test afterwards ... after good testing result, yes, them it make sense do take a closer look and install and learn  python and pytorch ...

**Comment by mathildecaron31** [comment]
Hi @Armin234 

I am not currently familiar with ONNX but I can definitely take a look next week.

**Comment by Armin234** [comment]
Hi @mathildecaron31, thanks 👍

**Comment by mathildecaron31** [comment]
Hi @Armin234 

I have included some ONNX models. You can use them only with Bx3x224x224 (where B is the batch size) inputs. The model's output will be of size `BxD` where `D` is the feature dimensionality (`D=384` for DeiT-S and `D=768` for ViT-B). This output is the representation of the image. You can use this representation for k-nn evaluations for example.

https://github.com/facebookresearch/dino/commit/82d28b4e93d12b309aa04edeb962eff6d7fbecf6

**Comment by Armin234** [comment]
Hi @mathildecaron31, thanks for or effort, now I can test your models, only the download of the resnet isn*t working, it give me an
access forbidden error.

Regards
Armin

**Comment by mathildecaron31** [comment]
Ha yes I have forgotten to add resnet50...

**Comment by mathildecaron31** [comment]
I have included the resnet50 onnx model. Sorry for the delay...
