### ISSUE TITLE
DistributedDataParallel device_ids and output_device argument only work with signle-device CUDA modules

### ISSUE THREAD

**Issue by Lost2Dream** [facebookresearch/dino#143]
As tiltle, I have prepared the environment with pytorch 1.5.0, python 3.7.5
and cuda, cudnn are ready
the GPU is only one , NVIDIA GeForce GTX 1080Ti
![IMG_20211013_142319](https://user-images.githubusercontent.com/50065384/137233670-6fa213a9-3b04-428e-909e-5debed355024.jpg)

**Comment by Lost2Dream** [comment]
And I use bing and google, there is no useful result

**Comment by mathildecaron31** [comment]
Hi @Lost2Dream 
I think this is a problem of Pytorch/CUDA compilation and not related to DINO codebase. Have you managed to solve your issue ?

**Comment by pasquale90** [comment]
I ask in favor of a friend but did you manage to run it on a 1080ti? If you did, could you please share the dependencies installed or at least some insights in general? Thank you in advance!
