### ISSUE TITLE
Could you release the checkpoint trained with 100 epoch and 300 epoch?

### ISSUE THREAD

**Issue by OliverRensu** [facebookresearch/dino#148]
You provide command of Vanilla DINO training and Boosting DINO performance, could you release the corresponding checkpoints?

**Comment by woctezuma** [comment]
Loosely related:
- #145

**Comment by guangdongliang** [comment]
> Vanilla: https://dl.fbaipublicfiles.com/dino/example_runs_logs/dino_vanilla_vitsmall16_checkpoint.pth Boosted: https://dl.fbaipublicfiles.com/dino/example_runs_logs/dino_boost_vitsmall16_checkpoint.pth

@mathildecaron31 have your train Vanilla on 16 \* v100 ? Did the k-nn performance decrease ?
