### ISSUE TITLE
Runtime Error: No rendezvous handler for env://

### ISSUE THREAD

**Issue by CA4GitHub** [facebookresearch/dino#151]
Has the DINO source code been tested on Windows 10?

I've successfully used it on Ubuntu.  However, when I tried to use it on a Windows 10 computer, I received the error:

`Runtime Error: No rendezvous handler for env://`

The error mentioned line 82 in the torch distributed file rendezvous.py.

A little research came across this [github issue](https://github.com/PyTorchLightning/pytorch-lightning/issues/5358?force_isolation=true) which makes me think it could be a Windows 10 issue.  However, I'm not sure how to test the solution the link mentions (i.e. set accelerator to dp, where dp I think stands for data parallel; as opposed to ddp, distributed data parallel) with DINO.

**Comment by woctezuma** [comment]
> The error mentioned line 82 in the torch distributed file rendezvous.py.

As a blind guess, I would try to set an `accelerator` parameter with the command-line calling `torch.distributed.launch`.

cf. README: https://github.com/facebookresearch/dino#vanilla-dino-training-sauropod

cf. doc https://pytorch.org/docs/stable/distributed.html

**Comment by mathildecaron31** [comment]
Hello @CA4GitHub 

This code has not been tested on Windows unfortunately. I don't think I can help you :/
