### ISSUE TITLE
A question regarding the hardware used for training

### ISSUE THREAD

**Issue by Puranjay-del-Mishra** [facebookresearch/dino#152]
My apologies if this is not the place to ask this, but what were the GPU specifications ( VRAM, tensor cores) used in training "vits" ? Also it would really be helpful if I could know the exact server/cloud service used for training. Thank you!

**Comment by woctezuma** [comment]
> Also it would really be helpful if I could know the exact server/cloud service used for training.

I doubt they would share this piece of info. It is Facebook, so they have their own clusters imo.

**Comment by mathildecaron31** [comment]
I have nothing to add to @woctezuma's reply :)

I am closing the issue, feel free to reopen if needed.
