### ISSUE TITLE
Semi-supervised extension

### ISSUE THREAD

**Issue by clane9** [facebookresearch/dino#153]
Thank you for releasing this code! DINO seems like it would naturally extend to the semi-supervised setting by adding a classification loss for any samples with labels. Have you tried something like this? Does it work? Thanks in advance!

**Comment by mathildecaron31** [comment]
Hi @clane9 

Thanks for your interest in this work. That is actually a good remark and we quickly tried some semi-supervised extension of the DINO loss. However, we found that different data augmentations were optimal for the supervised / SSL part of the loss and so the overall pipeline was a bit complicated.

On another side, I'd recommend our [ICCV21 paper PAWS](https://arxiv.org/pdf/2104.13963.pdf) that extends [SwAV](https://arxiv.org/pdf/2006.09882.pdf) to semi-supervised learning.
