### ISSUE TITLE
Google Landmark Pretrained model

### ISSUE THREAD

**Issue by Shiro-LK** [facebookresearch/dino#156]
Hello,

Thank you for sharing the code of your interesting paper.

I have few question about the pretrained model on google landmark, which parameters did you use for the training ? 
Does the model was pre trained on imagenet previously ? How long does it take and with which Hardware ?

**Comment by woctezuma** [comment]
Relevant issues:

> See instructions to repro here: https://github.com/facebookresearch/dino#evaluation-image-retrieval-on-revisited-oxford-and-paris

- https://github.com/facebookresearch/dino/issues/87#issuecomment-880862137

> DINO has been working out of the box with the default parameters specified in this repo.

- https://github.com/facebookresearch/dino/issues/43#issuecomment-843396233

**Comment by mathildecaron31** [comment]
Hi @Shiro-LK 

Google Landmark DINO checkpoint is at https://dl.fbaipublicfiles.com/dino/dino_vitsmall16_googlelandmark_pretrain/dino_vitsmall16_googlelandmark_pretrain.pth

It was not pre-trained on ImageNet. I used the parameters from the `boosting` setting: https://github.com/facebookresearch/dino#boosting-dino-performance-t-rex

Hope that helps

**Comment by Shiro-LK** [comment]
@mathildecaron31  @woctezuma  Thanks you for your reply. It is very helpful. 
Last question, what was the image size used for training ? 
When I look at the note in the github repo, it proposes to use image size of 512 in the example for the image retrieval for Paris and 224 for Oxford. I thought transformers had a fixed image size. Which one should I use ? 
Is it a typo ?

**Comment by mathildecaron31** [comment]
During dino pre-training we use 224x224 inputs (and 96x96 for the local crops).
