### ISSUE TITLE
The patch size is hard coded in hubconf.py

### ISSUE THREAD

**Issue by xhlulu** [facebookresearch/dino#18]
For example:
https://github.com/facebookresearch/dino/blob/8aa93fdc90eae4b183c4e3c005174a9f634ecfbf/hubconf.py#L55-L61

Is that intended (i.e. the model will not work if `patch_size=16`)? If not I'd be happy to contribute a PR to fix that.

**Comment by user1234554321** [comment]
I think it is intended. The '8' part in `dino_vitb8` is refers to the `patch_size` I believe ? If I you see the function before that `dino_vitb16`, it uses `patch_size=16`. Also, looking at the model, I believe the `patch_size` is used as the `kernel_size` and `stride` in the `PatchEmbed` (which is done using Conv2d). So, changing the `patch_size` would change the kernel (and thus parameters of the model).

**Comment by xhlulu** [comment]
@user1234554321 Thank you for the explanation! This answered my question :)
