### ISSUE TITLE
A mistake in the definition of height and weight?

### ISSUE THREAD

**Issue by Cohesion97** [facebookresearch/dino#180]
https://github.com/facebookresearch/dino/blob/cb711401860da580817918b9167ed73e3eef3dcf/visualize_attention.py#L173

In `visualize_attention.py`, after the transforms, I think the image shape should be [c, h, w], shouldn't it?  Is there a mistake in the definition of height and weight?

**Comment by woctezuma** [comment]
- #111

**Comment by Cohesion97** [comment]
@woctezuma Thanks for your link! It is true that it still works fine with square images. 
Since it has been discussed, I will close the issue.
