### ISSUE TITLE
how to get initial center in DINOLoss

### ISSUE THREAD

**Issue by chagmgang** [facebookresearch/dino#182]
I know how to calculate the self.center in DINOLoss iteravely.
However, I cannot find the initial value of self.center in DINOLoss at anywhere.

https://github.com/facebookresearch/dino/blob/main/main_dino.py#L416

**Comment by woctezuma** [comment]
https://github.com/facebookresearch/dino/blob/cb711401860da580817918b9167ed73e3eef3dcf/main_dino.py#L371
