### ISSUE TITLE
torch.distributed problem when runnning on a single GPU, custom dataset

### ISSUE THREAD

**Issue by amandalucasp** [facebookresearch/dino#185]
Hi! First of all, congratulations on your work, and thanks for sharing the code! :)

I'm running `main_dino.py` on a custom dataset I coded from scratch. Once training is done, the script does not finish -- as if there was some process waiting to be finished. 
I'm running training on a single GPU, with the following command:

```
python -m torch.distributed.launch --nproc_per_node=1 main_dino.py --arch vit_small --batch_size 16 --patch_size 16 --out_dim 65536 --norm_last_layer False --warmup_teacher_temp 0.04 --teacher_temp 0.07 --warmup_teacher_temp_epochs 30 --use_fp16 False --weight_decay 0.04 --clip_grad 0 --epochs 400 --freeze_last_layer 1 --lr 0.0005 --warmup_epochs 10 --min_lr 1e-5 --local_crops_number 10 --seed 0 --num_workers 10 --world_size 16 --optimizer "adamw" --momentum_teacher 0.996 --use_bn_in_head False --drop_path_rate 0.1

```

The code gets stuck after printing the training time. When I check on the System Monitor, I have two python threads running, one sleep and one that keeps switching between sleep and in execution.

Any ideas on what might be causing this issue, and how to solve it? At first I thought it might be related to uneven samples, but even after fixing it the problem still remains. Thanks!

**Comment by woctezuma** [comment]
> The code gets stuck after printing the training time.

Training time should be the last thing printed in `main_dino.py`:

https://github.com/facebookresearch/dino/blob/cb711401860da580817918b9167ed73e3eef3dcf/main_dino.py#L298

So I think there is something else at work causing the issue here.

**Comment by amandalucasp** [comment]
Yeah, as I mentioned, I do get the Training Time. As in the last experiment I executed here
<img width="710" alt="Captura de Tela 2022-03-30 às 08 48 40" src="https://user-images.githubusercontent.com/84402263/160827767-232ea39e-ab78-4f8c-8e7b-28cf1940147e.png">
And then on system monitor, I have one thread, sleeping.
