### ISSUE TITLE
ResNet50 DINOHead is different 

### ISSUE THREAD

**Issue by fawazsammani** [facebookresearch/dino#189]
Hi. Regarding the ResNet-50 full checkpoint that is uploaded, there appears to be a disagreement between the `DINOHead `in your code. In [main_dino.py](https://github.com/facebookresearch/dino/blob/main/main_dino.py) you leave the `nlayers=3`,  `hidden_dim=2048` and you use `nn.utils.weight_norm(nn.Linear(bottleneck_dim, out_dim, bias=False))`. 

However in the checkpoint you provided [here](https://dl.fbaipublicfiles.com/dino/dino_resnet50_pretrain/dino_resnet50_pretrain_full_checkpoint.pth) by doing:

```
for name, param in state_dic.items():
     print(name, param.shape)
```

I observe that `nlayers=2`, `hidden_dim=4096` and `last_layer` is not wrapped in `nn.utils.weight_norm`. Am I doing something wrong or is it a mistake on your side?

**Comment by woctezuma** [comment]
Maybe kind of related:
- https://github.com/facebookresearch/dino/issues/30#issuecomment-840595929
- https://github.com/facebookresearch/dino/issues/126#issuecomment-923687842

**Comment by fawazsammani** [comment]
I checked those issues before I opened this issue, they are not really related to what I'm asking. Anyways by changing the DINOHead i am able to load it and all keys match. Thanks!

**Comment by Noodles-321** [comment]
Hi, I just encountered the same problem. Could you please share how you changed the DINOHead for ResNet50?

**Comment by fawazsammani** [comment]
@Noodles-321 it like that
```
student_head = DINOHead(in_dim = embed_dim, out_dim = 60000, use_bn=True, norm_last_layer=True, nlayers=2, hidden_dim=4096, bottleneck_dim=256)
teacher_head = DINOHead(in_dim = embed_dim, out_dim = 60000, use_bn =True, norm_last_layer=True, nlayers=2, hidden_dim=4096, bottleneck_dim=256)
student_head.last_layer = nn.Linear(256, 60000, bias = False)
teacher_head.last_layer = nn.Linear(256, 60000, bias = False)
```
