### ISSUE TITLE
license

### ISSUE THREAD

**Issue by AK391** [facebookresearch/dino#20]
would it be ok to make a web demo for the attention map visualization part on https://gradio.app/ under the current license?

**Comment by xhlulu** [comment]
I find licenses hard to directly read, but since this is a CC-BY-NC 4.0 you can refer to the [excellent summary by creative commons](https://creativecommons.org/licenses/by-nc/4.0/).

**Comment by mathildecaron31** [comment]
Hi @AK391,

Does @xhlulu reply answer your question ? If yes, I let you close the issue. Thanks a lot for your interest :)

**Comment by AK391** [comment]
@mathildecaron31 @xhlulu I guess the gradio hub would count as a commercial use since it is hosted there so it is not allowed thanks

**Comment by mathildecaron31** [comment]
Hi @AK391 
FYI we have updated our license. See: https://github.com/facebookresearch/dino/commit/a52c63ba27ae15856a5d99e42c5a1b82daa902d8
