### ISSUE TITLE
hello what I would need to do to apply it to 3d medical imaging setting

### ISSUE THREAD

**Issue by jakubMitura14** [facebookresearch/dino#210]
Hello, I would like to use your algorithm for the 3d setting (magnetic resonance imaging of the prostate gland). I have only image-level labels, and your algorithm seems very interesting. What would I need to do to adapt it for a 3-dimensional setting?

**Comment by abebe9849** [comment]
you can use 2.5d model.
pretrain:stack 3 adjacent slices→training DINO for 2d model
fine tuniung: training MIL(e.g:https://www.kaggle.com/competitions/rsna-2022-cervical-spine-fracture-detection/discussion/362607 ) with DINO-pretrained-backbone.

**Comment by jakubMitura14** [comment]
Thanks!

**Comment by abebe9849** [comment]
@jakubMitura14 

RSNA2022 also did not provide per-slice annotations. My intention is to treat slices like "WSI's tiles" and study MultiInstanceLearning. DINO can be used for the slice embedding part of MIL. I think it depends on the task whether it is better to use DINO up to the aggregation layer. (e.g: https://github.com/mahmoodlab/HIPT)

**Comment by abebe9849** [comment]
@jakubMitura14 
RSNA2022 also did not provide per-slice annotations. Using MIL eliminates the need for slice-wise annotation. It seems that self-supervised learning can also be used for aggregation layers. (e.g: https://github.com/mahmoodlab/HIPT)

**Comment by jakubMitura14** [comment]
thanks!

**Comment by abebe9849** [comment]
https://github.com/yeerwen/DeSD seems a 3D version of DINO. 
@jakubMitura14 

I hope this would help you.

**Comment by jakubMitura14** [comment]
Perfect -Thank You !
