### ISSUE TITLE
Getting image features from finetuned checkpoint 

### ISSUE THREAD

**Issue by MikeMACintosh** [facebookresearch/dino#216]
I only want to get the features of the image, I didn't want to get into VIT's head and do classification etc, I only want to image embedding.
I funetune DINO on custom dataset and having checkpoint "checkpoint0005.pth" and i do:
model_fb = torch.hub.load('facebookresearch/dino:main', 'dino_vits16')
model_fb.load_state_dict(torch.load('dino_result/checkpoint0005.pth', map_location='cpu'))
model_fb.eval()

and getting error: RuntimeError: Error(s) loading state_dict for VisionTransformer and list of invalid keys

next I would like to do for example:

input_image = Image.open(image_path).convert("RGB")
convert_to_tensor = transforms.Compose([transforms.PILToTensor()])
input_tensor = convert_to_tensor(input_image)
input_batch = input_tensor.unsqueeze(0)
with torch.no_grad():
    embedding = torch.flatten(model(input_batch)[0]).cpu().data.numpy()

what i do wrong?

**Comment by MikeMACintosh** [comment]
[solved](https://github.com/facebookresearch/dino/issues/217)

**Comment by XiaoQiSAMA** [comment]
Hi @MikeMACintosh 

I have the same problem, I also confuse about how to get embedding. In eval_linear.py, the author used get_intermediate_layers() and torch.cat() to get image features, but in eval_knn.py they used model(input) directly.
It's kind of weird. 

So, I want to know how you get image features?
