### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [384, 3, 8, 8], expected input[1, 0, 512, 585] to have 3 channels, but got 0 channels instead

### ISSUE THREAD

**Issue by cishwarya** [facebookresearch/dino#24]
Hi all,  I have problem running the inference script, https://gist.github.com/aquadzn/32ac53aa6e485e7c3e09b1a0914f7422

The images I use are originally grayscale and have been converted to 3 channels. Now the shape of my images are (427, 488, 3)

When I run predict_video(args) I get the following error. Could you please help me here? thanks

 I converted the images to 3 channels with the following code.

```
import cv2
import numpy as np
def saveAsRGB(image_path):
  for filepath in sorted(glob.iglob(image_path + "/*")):
    img = cv2.imread(filepath)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img2 = np.zeros_like(img)
    img2[:,:,0] = gray
    img2[:,:,1] = gray
    img2[:,:,2] = gray
    cv2.imwrite(filepath, img2)

 img = cv2.imread ("~input/finalImg_242.png")
 print(img.shape) #output : (427, 488, 3)
```
Also as you could see from the below code, inside predict_video(args) function, I tried to print the shape of the image and confirmed that it has 3 channels ([3, 512, 585]).

```
import numpy as np
import cv2
import glob
def predict_video(args):

    for filepath in sorted(glob.iglob(args.image_path + "/*")):
        print("filepath",filepath)
        img = Image.open(filepath)
        img = img.convert('RGB')
        transform = pth_transforms.Compose([
            pth_transforms.ToTensor(),
            pth_transforms.Resize(512),
            pth_transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225)),
        ])
        img = transform(img)

        print(".img.shape",img.shape)  # output is torch.Size([3, 512, 585])

```

**Error:**

RuntimeError Traceback (most recent call last)
in ()
----> 1 predict_video(args)

6 frames
in predict_video(args)
41
42
---> 43 attentions = model.forward_selfattention(img.cuda())
44
45 nh = attentions.shape[1] # number of head

~/vision_transformer.py in forward_selfattention(self, x)
220 B, nc, w, h = x.shape
221 N = self.pos_embed.shape[1] - 1
--> 222 x = self.patch_embed(x)
223
224 # interpolate patch embeddings

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
887 result = self._slow_forward(*input, **kwargs)
888 else:
--> 889 result = self.forward(*input, **kwargs)
890 for hook in itertools.chain(
891 _global_forward_hooks.values(),

~/vision_transformer.py in forward(self, x)
116 def forward(self, x):
117 B, C, H, W = x.shape
--> 118 x = self.proj(x).flatten(2).transpose(1, 2)
119 return x
120

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
887 result = self._slow_forward(*input, **kwargs)
888 else:
--> 889 result = self.forward(*input, **kwargs)
890 for hook in itertools.chain(
891 _global_forward_hooks.values(),

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py in forward(self, input)
397
398 def forward(self, input: Tensor) -> Tensor:
--> 399 return self._conv_forward(input, self.weight, self.bias)
400
401 class Conv3d(_ConvNd):

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/conv.py in _conv_forward(self, input, weight, bias)
394 _pair(0), self.dilation, self.groups)
395 return F.conv2d(input, weight, bias, self.stride,
--> 396 self.padding, self.dilation, self.groups)
397
398 def forward(self, input: Tensor) -> Tensor:

RuntimeError: Given groups=1, weight of size [384, 3, 8, 8], expected input[1, 0, 512, 585] to have 3 channels, but got 0 channels instead

**Comment by user1234554321** [comment]
Can you please print the shape of `img` just before this line 
`attentions = model.forward_selfattention(img.cuda())`

**Comment by cishwarya** [comment]
Thanks for your reply. I realized that I made a mistake in my code. Sorry for the inconvenient caused. Closing the issue.
