### ISSUE TITLE
Smaller model implementation

### ISSUE THREAD

**Issue by IgorKasianenko** [facebookresearch/dino#25]
Hello,

Do you have plans to check the performance of smaller models like mobilenet_v2 or v3 (they are available in torchvision_models)? 
If no, I may look into this task. Do you think that small CNN like mobilenet (with depth 1 or even 0.35) is capable of learning these representations?

**Comment by mathildecaron31** [comment]
Hi @IgorKasianenko 
Thanks for your interest in this work. I have not been experimented with smaller models at all, so I don't have much insight to provide unfortunately. I would be very interested in your findings if you plan to experiment with these models.

**Comment by IgorKasianenko** [comment]
Thank you for the reply.
I will consider training mobilenet model with your code base and reporting results in pool request. One thing that I want to validate, did you use all 1,281,167 images for training the resnet backbone?

> This dataset spans 1000 object classes and contains 1,281,167 training images, 50,000 validation images and 100,000 test images.

**Comment by mathildecaron31** [comment]
Awesome ! Yes I used all 1,281,167 training images.

**Comment by VishnuGopireddy** [comment]
Hi @mathildecaron31 any progress or update on DINO with mobilenet model??

**Comment by woctezuma** [comment]
I don't think Mathilde is training a MobileNet model. Only Igor mentioned it.

**Comment by VishnuGopireddy** [comment]
Hi @IgorKasianenko , any progress or update on DINO with mobilenet/ resnet18/34 models??

**Comment by IgorKasianenko** [comment]
Hi @VishnuGopireddy I didn't have time to work on this, can't commit to any timeline, but if I will train it I will let you and everyone in this thread know.
