### ISSUE TITLE
Question regarding patch retrieval demo

### ISSUE THREAD

**Issue by crypdick** [facebookresearch/dino#250]
I saw that you shared code for evaluating _image-level retrieval_ ([Issue](https://github.com/facebookresearch/dino/issues/87) & [code](https://github.com/facebookresearch/dino/blob/main/eval_image_retrieval.py)). I am keen to replicate the _patch-level retrieval_ from the official DINO demos [here](https://ssl-demos.metademolab.com/retrieval/openimages_patch/RetrievalResults?query_image=https%3A%2F%2Fc6.staticflickr.com%2F4%2F3176%2F2569091343_e5b64193f4_z.jpg).

Thank you for your guidance! If there are any code snippets or resourced that you can share to replicate the demo, I would be most grateful.

**Comment by Gugliebiagio** [comment]
Hi, have you tried to implement that?

**Comment by crypdick** [comment]
@Gugliebiagio You can't use the `forward` outputs because it slices out just the global [CLS] embedding: https://github.com/facebookresearch/dino/blob/main/vision_transformer.py#L214

Instead, you have to get the raw output using `get_intermediate_layers`:

```python
import torch

model = torch.hub.load("facebookresearch/dino:main", "dino_vits16")
img = torch.randn(1, 3, 224, 224)
features = model(img)
print(features.shape)  # torch.Size([1, 384]) -- already pooled

features = model.get_intermediate_layers(img, len(model.blocks))
features = features[-1]  # residual stream @ final block
print([features.shape])  # torch.Size([1, 197, 384])
```

In this example, you have 1+14^2 embeddings, each which is 384-d. You can drop the first one, and map the 196 embeddings back to the 196 patches.
