### ISSUE TITLE
Model is not defined

### ISSUE THREAD

**Issue by zuenko** [facebookresearch/dino#26]
https://github.com/facebookresearch/dino/blob/534f37f000a10afff97c0d96ec4df81875193699/main_dino.py#L316

Should be
`param_norms = utils.clip_gradients(student, args.clip_grad)`

**Comment by mathildecaron31** [comment]
Hi @zuenko, ha yes that's a good catch thx !!

https://github.com/facebookresearch/dino/commit/8c724f5c0ec3009f3674792b20d51b27eca4214d
