### ISSUE TITLE
Choice of out_dim

### ISSUE THREAD

**Issue by JunboShen** [facebookresearch/dino#279]
The default out_dim is 65536. I trained using 65536 on a custom dataset but the loss did not decrease, or decrease very slowly. If I chose a smaller out_dim, the loss seemed to converge much faster. It is okay/recommended to use a smaller out_dim, let's say change from 65535 to 1024, 2048, etc.

**Comment by wangh09** [comment]
Of course. iBOT, another work based on DINO and inspired DINOv2, chose dim=8192 (though with an extra MIM head).
