### ISSUE TITLE
What is outputted by the pretrained model?

### ISSUE THREAD

**Issue by Timalph** [facebookresearch/dino#29]
I ran 

deits16 = torch.hub.load('facebookresearch/dino:main', 'dino_deits16') 

to retrieve the pretrained model. This takes an image and outputs a vector of length 384. What is this vector? Is this a representation of the image? And if it is, can I use this pretrained network to create representations of images/patches that I can use for clustering?

Secondly,

in the visualize_attention.py file from line 199 - 206 we save images for all attention heads in a for loop. How are the images in the paper generated then as those are single images? Are they a combination of the heatmaps outputted by the model? And if they are, how are they combined? By average or by summation?

**Comment by MalharJ** [comment]
+1. When load pretrained resnet-50 and run `model.forward()` on a `torch.Size([1, 3, 224, 224])` image I get a tensor with shape `torch.Size([1, 1000])`. If we do the same with `dino_deits16` I get a tensor with shape `torch.Size([1, 384])`. How can I obtain ImageNet top-1 accuracy with this?

**Comment by mathildecaron31** [comment]
Hi @Timalph 

1) The vector of length 384 is the representation of the image. More precisely it is the output [CLS] token. When evaluating with k-nn we use this representation for example. I think it is a good idea to use this for clustering indeed :).

2) Images from Figure 1 and Figure 4 are generated precisely with this code. We simply show a single head in Figures 1/4 out of the 6 heads and we arbitrarily choose this head. In Figure 3 we combine a certain number of different heads and each head has a different color.

Hope that helps

**Comment by mathildecaron31** [comment]
Hi @MalharJ 
Mmh thanks for flagging this inconsistency. It may be clearer if all models output a representation (and not a score over the 1000 classes of ImageNet). I'm going to change the code slightly so resnet-50 outputs a representation, in this case the dimensionality is 2048.

I will try to do a colab shortly to explain more clearly the inference with our models.
