### ISSUE TITLE
Why PatchEmbed do not have norm layer?

### ISSUE THREAD

**Issue by gaopengcuhk** [facebookresearch/dino#33]
Compared with DeiT/ViT in a supervised learning setting, it seems like your PatchEmbed does not have a norm layer. Can you explain your choice?

**Comment by mathildecaron31** [comment]
Hi @gaopengcuhk 

From my understanding, `PatchEmbed` does not have a norm layer neither in DeiT, ViT nor DINO. We are following exactly the architecture DeiT-S from `deit` codebase: https://github.com/facebookresearch/deit/blob/cb29b5efd522a0ac83d64aa8b41fe27cead3a030/models.py#L77-L89

If you take a look at `timm` codebase https://github.com/rwightman/pytorch-image-models/blob/c16d65a8a7a27c0a0418cf601a5ee0fcbb740135/timm/models/vision_transformer.py#L224-L225 and https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/patch_embed.py
 you see that `norm_layer` is set to `None`.
