### ISSUE TITLE
About the immediate layer feature

### ISSUE THREAD

**Issue by Youskrpig** [facebookresearch/dino#35]
How to extract the immediate layer feature in Vit_b8 model? 
I tried:
 model = torch.hub.load('facebookresearch/dino:main', 'dino_vitb8')
 modules = list(model.children())[:-2]
 model = nn.Sequential(*modules)
but model(x.to(device)) error occur: forward() takes 1 argument but 2 were given

**Comment by mathildecaron31** [comment]
Hi @Youskrpig 

You can use this:
https://github.com/facebookresearch/dino/blob/6687929d7cdc2e7a5150f6e24c2b6713293944ac/vision_transformer.py#L225-L233

For example use the following code:
```
model = torch.hub.load('facebookresearch/dino:main', 'dino_vitb8', force_reload=True)
intermediate_blocks = model.get_intermediate_layers(x.to(device), n=12)
```
`intermediate_blocks` is a list of size `12` in this case with each element of the list corresponding to a different block. For example, `intermediate_blocks[-1]` corresponds to the last block and is of size `B x (N + 1) x C` where `B` is the batch size in `x`, `N` is the number of patch tokens (N=784 for 224x224 inputs and patchsize 8) and `C` is the dimensionality (768 for vit-base).

Hope that helps.
