### ISSUE TITLE
Video Instance Segmentation task

### ISSUE THREAD

**Issue by npmhung** [facebookresearch/dino#37]
In this task, how do you propagate the label from previous frames?

Specifically,
- What kind of distance do you use in the kNN (cosine or L2)?
- How many blocks did you use as the feature of a token?

**Comment by mathildecaron31** [comment]
Hi @npmhung, thanks for your interest. I have included the code for DAVIS 2017 Video object segmentation.

We use cosine distance for kNN.
We use one block (the last one) for the feature of a token.

Closing because related to https://github.com/facebookresearch/dino/issues/4
