### ISSUE TITLE
Will you release code to replicate Table 5: DAVIS 2017 Video object segmentation?

### ISSUE THREAD

**Issue by gaopengcuhk** [facebookresearch/dino#4]
As the title implies

**Comment by mathildecaron31** [comment]
Hi @gaopengcuhk 

Yes, I am planning to do that in the coming days. Need to clean the code a bit before !

**Comment by mathildecaron31** [comment]
https://github.com/facebookresearch/dino#evaluation-davis-2017-video-object-segmentation
