### ISSUE TITLE
Error when loading pretrained checkpoint for finetunning

### ISSUE THREAD

**Issue by vobecant** [facebookresearch/dino#40]
Dear authors,

thank you very much for this repo. I would like to use the pre-trained weights and finetune the network for a different dataset using self-supervised learning with DINO.
However, when I try to use the code, I cannot load the optimizer's state and I get the following output:

```
Found checkpoint at ./dino_ft_workdir/checkpoint.pth
=> loaded student from checkpoint './dino_ft_workdir/checkpoint.pth' with msg <All keys matched successfully>
=> loaded teacher from checkpoint './dino_ft_workdir/checkpoint.pth' with msg <All keys matched successfully>
=> loaded optimizer from checkpoint './dino_ft_workdir/checkpoint.pth'
=> failed to load fp16_scaler from checkpoint './dino_ft_workdir/checkpoint.pth'
=> failed to load dino_loss from checkpoint './dino_ft_workdir/checkpoint.pth'
```
fp16_scaler and dino_loss are not in the checkpoint so it is clear why they are not loaded.
I found out that the problem with the optimizer is caused by this:
```
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group.
```

Is there anyone who would be able to help me? 

Thank you very much in advance!

**Comment by woctezuma** [comment]
https://github.com/facebookresearch/dino/issues/30#issuecomment-840595929
