### ISSUE TITLE
Question: Supervised Attention Visualization

### ISSUE THREAD

**Issue by KeremTurgutlu** [facebookresearch/dino#42]
I was wondering about the attention maps used for visualizing the supervised training model. As far as I can understand, in the source code [last layer attention weights](https://github.com/facebookresearch/dino/blob/59478f4a91210f7eb93d6632559b8b9a6c2d0e70/vision_transformer.py#L216) are used to visualize for saliency masks. Is this same approach used for visualizing the supervised model for the visual comparison we have in Figure 4 of the paper?

If so, in papers such as [Quantifying Attention Flow in Transformers](https://arxiv.org/abs/2005.00928) it is argued that final attention maps can't be directly mapped back to input tokens in a meaningful way since information is mixed during forward propagation of multiple self-attention blocks.  What are your views on this?

Definitely, having saliency maps as a byproduct of self-supervised training is way more valuable than supervised training in the sense of zero shot learning. I was curious if last layer attention maps are used during supervised visualizations wouldn't it be more fair to use an approach like attention-flow instead? Also, would using this approach give different results for ViTs trained with DINO? Also, I am not sure if we can make sense of different heads with attention flow approach, and its pretty cool to see that different heads are able to localize into different objects in the case of DINO.

Thank you! :)

**Comment by mathildecaron31** [comment]
Hi @KeremTurgutlu 

Thanks for sharing your thoughts and the pointers.

Yes we use exactly the same approach when visualizing the self-attention maps with either DINO or supervised trained ViTs.

We were indeed very surprised to see segmentation patterns emerge directly into the self-attention modules. We wanted to show that this is a particularity of training vits with SSL. It is possible that extracting segmentations from supervisedly trained models is also possible, but the fact that it is directly available in the self-attention when trained with SSL was the property we wanted to highlight.

My intuition about why we obtain these maps would be that the SSL objective (i.e. learning invariance to crops) is more challenging than supervised label classif. For example, to predict a dog's head from its leg and vice-versa the system needs to somehow understand and model the whole structure of the dog. In label classif, the system does not need to predict part from part nor whole from part, but simply label "dog" from head and label "dog" from leg, which may be in essence an easier objective and might not require to model in such precision the relation between the head and the leg.

**Comment by KeremTurgutlu** [comment]
Thanks a lot for the detailed explanation, its great to hear all these intuitions. I've been exploring several ssl frameworks for a while now as my own independent research. SwAV gives exceptional results in practice across different datasets when transferred to downstream task, as you explained multi crop training and forcing model to learn multiple features probably is the explanation behind it. I also started thinking about this property of multi crop training in more depth after seeing this work https://www.microsoft.com/en-us/research/blog/three-mysteries-in-deep-learning-ensemble-knowledge-distillation-and-self-distillation/. Maybe SwAV,DINO already learns features about objects which can be possible with only some sophisticated data augmentation or model ensembling:

```
In our new work, we propose studying a common structure that can be found in many of the datasets where deep learning excels. In vision datasets in particular, the object can usually be classified using multiple views. For example, a car image can be classified as a car by looking at the headlights, the wheels, or the windows. For a typical placement of a car in images, we can observe all these features, and it suffices to use one of the features to classify it as a car. However, there are some car images taken from a particular angle, where one or more of these features are missing. 
```

Thanks for all your work in the field :)

**Comment by mathildecaron31** [comment]
Thanks for your kind words again and good luck with your research :)
