### ISSUE TITLE
Are the pretrained weights from the student or teacher model?

### ISSUE THREAD

**Issue by bfialkoff** [facebookresearch/dino#44]
I dont understand which of the two models are later used for inference is it the student or teach? Are the pretrained weights provided from the teacher or the student network?

**Comment by woctezuma** [comment]
> Are the pretrained weights provided from the teacher or the student network?

Everything is provided.

![Everything](https://i.imgur.com/AO4jkXT.png)

**Comment by bfialkoff** [comment]
Thanks for the clarification. I guess what I meant was in the video_generation script when we load a model, we are then loading the student or the backbone? Backbone to the base model and head refers to the part of the architecture that turns it into the student model?

**Comment by mathildecaron31** [comment]
Hi @bfialkoff 

The weights from the `backbone only` files are from the teacher, and results from our paper are obtained from the teacher weights as well. We have indeed shown in our paper that the teacher is performing better than the student in general.

Therefore, when using the video_generation script it is loading from teacher weights (though the visualization are nearly the same if you use the student weights in that case).

For any of our evaluation scripts, if you want to evaluate the student weights instead you can do so by specifying the path towards the full checkpoint with the `--pretrained_weights` argument and specifying `--checkpoint_key student`.

Hope that helps

**Comment by mathildecaron31** [comment]
@woctezuma thanks for helping to reply to this issue.

I have a minor remark. Our ultimate goal is to obtain the best model possible in an unsupervised way. We train the student with SGD and the teacher is an EMA of that student. We've found that the teacher is performing better than the student and that is why our final model used in downstream tasks in that of the teacher.

**Comment by woctezuma** [comment]
> 
> 
> @woctezuma thanks for helping to reply to this issue.
> 
> I have a minor remark. Our ultimate goal is to obtain the best model possible in an unsupervised way. We train the student with SGD and the teacher is an EMA of that student. We've found that the teacher is performing better than the student and that is why our final model used in downstream tasks is the teacher.

Oops, it looks like I was confused about that! Thanks for clearing that up! Hopefully I have not confused others!
