### ISSUE TITLE
Advice about the evaluation script on Video Object Segmentation

### ISSUE THREAD

**Issue by wuyongfa-genius** [facebookresearch/dino#45]
First, Thanks for your excellent work on self-supervised ViTs. It is very impressing to see the visulaizations of the attentions. Just a little advice about the evaluation script on Video Object Segmentation. I noticed that the script computes (1+n_last_frames) source frame features everytime when threre is a new target frame, which is unnecessary. In fact we can just put (1+n_last_frames) source frame features into the Queue and instead just compute target frame(current frame to propagate)'s feature, which will save much computation and thus making the evaluation much faster.
Of course this is not the focus of this study. Just a little advice.  *_*

**Comment by mathildecaron31** [comment]
Hi @wuyongfa-genius 
Thanks for the kind words and your interest.
Thanks for raising this issue, that is a very good remark. Please feel free to propose a PR if you want, that would be super helpful. I don't have much bandwidth to work on this myself.
