### ISSUE TITLE
HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by 15m43lk4155y** [facebookresearch/dino#5]
None of the pre-trained models is available in PyTorch hub the code raises an HTTPError: HTTP Error 404: Not Found.

**Comment by xhlulu** [comment]
The default branch for torch hub load is master, but `facebookresearch/dino` uses `main`, so you need to specify the branch you are downloading, e.g.
```
deits16 = torch.hub.load('facebookresearch/dino:main', 'dino_deits16')
```

**Comment by miraodasilva** [comment]
> The default branch for torch hub load is master, but `facebookresearch/dino` uses `main`, so you need to specify the branch you are downloading, e.g.
> 
> ```python
> deits16 = torch.hub.load('facebookresearch/dino:main', 'dino_deits16')
> ```

![image](https://user-images.githubusercontent.com/17463598/116790756-ea2fd700-aaad-11eb-8e71-92c0414be2cb.png)
