### ISSUE TITLE
visualize_attention.py will only work on GPU

### ISSUE THREAD

**Issue by xhlulu** [facebookresearch/dino#7]
It seems like the script was designed to only run on GPU:
https://github.com/facebookresearch/dino/blob/6f51bb16fb5dfd16ea8fb36786f144dbd3cfe228/visualize_attention.py#L106

Wouldn't it be more flexible if it was instead:
```python
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
model.to(device)
```

**Comment by mathildecaron31** [comment]
Thanks a lot @xhlulu 
I have commited your suggestion: https://github.com/facebookresearch/dino/commit/1d06521adfc53c80dece1a74902f718873e9821d

**Comment by xhlulu** [comment]
Thank you!
