### ISSUE TITLE
Training getting killed at the end of the first epoch

### ISSUE THREAD

**Issue by ahof1704** [facebookresearch/dino#71]
Hi,

I am trying to train DINO on my dataset. I did the minimum of modifications on the architecture necessary for the analysis. Here is the list of input parameters I am using:
```
args.world_size:  1
| distributed init (rank 0): env://
git:
  sha: 4b96393c4c877d127cff9f077468e4a1cc2b5e2d, status: has uncommited changes, branch: main

arch: vit_small
batch_size_per_gpu: 64
checkpoint_key: teacher
clip_grad: 3.0
dataset: <__main__.MyDataset object at 0x2ba3acb79e80>
dist_url: env://
epochs: 100
freeze_last_layer: 1
local_crops_number: 8
local_rank: 0
lr: 0.0005
min_lr: 1e-06
momentum_teacher: 0.996
ngpus: 1
nodes: 1
norm_last_layer: True
num_workers: 1
optimizer: adamw
out_dim: 65536
output_dir: ./out
partition: scavenge_gpu
patch_size: 16
pretrained_weights: ./input_fineTunning/output/checkpoint.pth
rank: 0
saveckp_freq: 20
seed: 0
teacher_temp: 0.04
threshold: 0.6
timeout: 2800
use_bn_in_head: False
use_fp16: True
warmup_epochs: 10
warmup_teacher_temp: 0.04
warmup_teacher_temp_epochs: 0
weight_decay: 0.04
weight_decay_end: 0.4
world_size: 1
Data loaded: there are 100000 images.
len(data_loader): 1562
Student and Teacher are built: they are both vit_small network.
```
The training goes for the first epoch, but at the end, I get the following error:
```
Epoch: [0/100]  [1560/1562]  eta: 0:00:00  loss: 7.877726 (9.913200)  lr: 0.000012 (0.000006)  wd: 0.040087 (0.040030)  time: 0.389599  data: 0.000192  max mem: 3828
Epoch: [0/100]  [1561/1562]  eta: 0:00:00  loss: 7.895004 (9.912079)  lr: 0.000012 (0.000006)  wd: 0.040088 (0.040030)  time: 0.389602  data: 0.000190  max mem: 3828
Epoch: [0/100] Total time: 0:10:13 (0.392813 s / it)
Averaged stats: loss: 7.895004 (9.912079)  lr: 0.000012 (0.000006)  wd: 0.040088 (0.040030)
Killing subprocess 7421
Traceback (most recent call last):
  File "../lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "../lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "../lib/python3.9/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "../lib/python3.9/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "../lib/python3.9/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['../conda_envs/../bin/python', '-u', 'code_DINO.py', '--local_rank=0']' died with <Signals.SIGKILL: 9>.
```

FYI, the absolute paths are omitted. The error message above is not entirely clear to me. Could you provide any insight on what is going on here or how to obtain a more clear idea about the error? 

Thanks!

Extra details:
- The `code_DINO.py` loads and create my dataset object as well as define the parameters (`args`) to be used before calling `the main_dino.train_dino(args)`. 
- The I performing the training in a node in the cluster with a single node with one GPU, 6 CPUs and 12GB/CPU of RAM.

**Comment by mathildecaron31** [comment]
Hi @ahof1704 
Can you try adding several `print` statements in the code in order to identify what line precisely gets the training kill. I have never seen that error before.

**Comment by ahof1704** [comment]
Hi @mathildecaron31 

Thank you for your fast reply! I have added prints all over the code and things seem to be going well until the checkpoint needs to be saved. It seems to go fine through `train_one_epoch` in `main_dino.py`:
```
Epoch: [0/100]  [1561/1562]  eta: 0:00:00  loss: 7.535885 (9.885490)  lr: 0.000012 (0.000006)  wd: 0.040088 (0.040030)  time: 0.376230  data: 0.000327  max mem: 3828
Epoch: [0/100] Total time: 0:09:55 (0.381033 s / it)

[getting in synchronize_between_processes... done]
Averaged stats: loss: 7.535885 (9.885490)  lr: 0.000012 (0.000006)  wd: 0.040088 (0.040030)
```
Then, `save_on_master` is called and `is_main_process()` is True. When the process gets to `torch.save`, an empty (0B) checkpoint.pth is saved in my output directory, and the process gets killed.

The error message I sent you in my first message is obtained when I run my script directly from the terminal. When running from Jupyter I get the following (perhaps not that helpful neither):
```
[I 2021-06-08 16:15:56.066 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports
kernel 75581f52-e24d-4bc3-b8b9-f29256258fa0 restarted
```

Any suggestion will be greatly appreciated :)

Thanks

**Comment by ahof1704** [comment]
Hi @mathildecaron31 ,

Just to let you know I have found the problem. It was a mistake on my part regarding how I was passing my custom dataset inside `args` to `main_dino`, which caused `torch.save` to not work properly. It's a pity none of the error messages could indicate the problem clearly, but I am glad it is solved now :)

Thanks!

**Comment by mathildecaron31** [comment]
Good to hear @ahof1704 ! I am closing the issue in that case. Feel free to reach out again if needed.
