### ISSUE TITLE
How can i exttract features from vision? 

### ISSUE THREAD

**Issue by mathshangw** [facebookresearch/dino#72]
i need to extract features from vision transformer . How can i start ?

**Comment by woctezuma** [comment]
Start with one of these:
-   https://github.com/facebookresearch/dino/blob/main/eval_linear.py
-   https://github.com/facebookresearch/dino/blob/main/eval_knn.py

**Comment by mathildecaron31** [comment]
Hi @mathshangw 

You can take a look at https://github.com/facebookresearch/dino/blob/ba9edd18db78a99193005ef991e04d63984b25a8/eval_knn.py#L94-L138

Let me know if you have any questions

**Comment by woctezuma** [comment]
Also:
-   https://github.com/facebookresearch/dino/blob/main/eval_copy_detection.py
-   https://github.com/facebookresearch/dino/blob/main/eval_image_retrieval.py

**Comment by mathildecaron31** [comment]
@mathshangw have you been able to extract features as you wanted ? If yes, I let you close the issue. Otherwise, feel free to ask more questions and I will try to help.

**Comment by mathshangw** [comment]
sorry for the late reply . I tried the code but are these features for images before classifiying it .. I mean if I need to remove the output or classification layer to get the features . does it will be the same

**Comment by woctezuma** [comment]
> sorry for the late reply . I tried the code but are these features for images before classifiying it .. I mean if I need to remove the output or classification layer to get the features . does it will be the same

In the case of DINO, contrary to [Microsoft's BEiT](https://huggingface.co/transformers/master/model_doc/beit.html), yes.

**Comment by mathshangw** [comment]
Thanks  a lot for replying .. so excuse me 
does that right ? 
```
PATH = 'dino_resnet50_pretrain.pth'
model = dino_resnet50(pretrained=True)
model.load_state_dict(torch.load(PATH),strict=True)
```
then i can use model for the images i have to extract the features ?

**Comment by woctezuma** [comment]
It is possible that your code is equivalent, but I would follow the README and use this:
```python
import torch
resnet50 = torch.hub.load('facebookresearch/dino:main', 'dino_resnet50')
```

**Comment by mathshangw** [comment]
i tried your code but got 
`ImportError: cannot import name 'ViTFeatureExtractor'`

**Comment by woctezuma** [comment]
That is because you would need to install `transformers` first.

**Comment by mathshangw** [comment]
> That is because you would need to install `transformers` first.

i installed it using pip3 install transformers

**Comment by woctezuma** [comment]
If you want a minimal example without HuggingFace:

```python
from PIL import Image
import requests

def get_image(url):
  return Image.open(requests.get(url, stream=True).raw)
```

```python
from torchvision import transforms as pth_transforms

preprocess = pth_transforms.Compose([
        pth_transforms.Resize(256, interpolation=3),
        pth_transforms.CenterCrop(224),
        pth_transforms.ToTensor(),
        pth_transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225)),
    ])

def get_features(model, img):
  return model(preprocess(image).unsqueeze(0))
```

```python
import torch

resnet50 = torch.hub.load('facebookresearch/dino:main', 'dino_resnet50')

url = 'http://images.cocodataset.org/val2017/000000039769.jpg'
features = get_features(resnet50, get_image(url))
```

**Comment by mathshangw** [comment]
Thanks a lot .. excuse my last question at this point .. I'm trying to extract features for the images in a folder and save it as a list of arrays like this  

```
model = torch.hub.load('facebookresearch/dino:main', 'dino_resnet50')
for name in listdir(directory):

        filename=directory + '/' + name
        pil_img= load_img(filename, target_size=(224, 224,3))
        image=img_to_array(pil_img)
        img1 = torch.from_numpy(image).float() 
        images = img1.reshape((1, img1.shape[0], img1.shape[1], img1.shape[2]))
        vectors =model(images.permute(0,3,1,2))
        vec=vectors.detach().numpy()
        for ind in range(1):
            results.append(vec[ind])
    return results

```
does this the same as what you did ?

**Comment by mathshangw** [comment]
thanks a lot but excuse me how can i get the details about` preprocess(image)` method

**Comment by woctezuma** [comment]
The details are in my code snippet: resize, center-crop, normalization. Very simple pre-processing.

**Comment by mathshangw** [comment]
> The details are in my code snippet: resize, center-crop, normalization. This is a very simple pre-processing.

oh i didn't take my attention .. thanks a lot .. appreciating your help

**Comment by mathshangw** [comment]
excuse me if I did this line 
   
 ```
results=[ ]
  vec=model(preprocess(image).unsqueeze(0))
  vec1=vec.detach().cpu().numpy()
for ind in range(1):
            results.append(vec1[ind])
            print(results)
    return results
```
does that will be right if I want to save it in the list of arrays. cause i tried to remove this line   `vec1=vec.detach().cpu().numpy()` but got problem in Cuda and when i use CPU i got killed after some images

**Comment by mathshangw** [comment]
excuse me if I need the results like this 

```
[array([0.08252265, 0.03474489, 0.16312598, ..., 0.00343753, 1.8329982 ,
       0.18630761], dtype=float32), array([0.13601835, 0.54774034, 0.4879991 , ..., 0.42392948, 0.73435366,
       2.046327  ], dtype=float32), array([0.37708312, 1.1497548 , 0.7367149 , ..., 1.0371637 , 0.8308265 ,
       0.06164827], dtype=float32), array([0.32374394, 1.0856272 , 0.00293694, ..., 0.25312978, 0.23081133,
       2.281322  ], dtype=float32), array([0.05174663, 1.2037114 , 0.        , ..., 2.4387941 , 0.10406396,
       0.29335037], dtype=float32), .... , dtype=float32)]
```
did those lines

```
results=[ ]
 vec=model(preprocess(image).unsqueeze(0))
 vec1=vec.detach().cpu().numpy()
for ind in range(1):
           results.append(vec1[ind])
           print(results)
   return results
```

does that will be right if I want to save it in the list of arrays. cause i tried to remove this line `vec1=vec.detach().cpu().numpy() `but got problem in Cuda and when i use CPU i got killed after some images

**Comment by mathshangw** [comment]
> 

excuse me I'm back to your reply again .. what I got is, if I want to extract the features for the images **before** classifying it, removing the classification layer or not removing it , will not affect or change the features right ?

**Comment by mathshangw** [comment]
> > sorry for the late reply . I tried the code but are these features for images before classifiying it .. I mean if I need to remove the output or classification layer to get the features . does it will be the same
> 
> In the case of [Facebook's DINO](https://huggingface.co/facebook/dino-vitb16) ([hugs's documentation](https://huggingface.co/transformers/master/model_doc/vit.html?highlight=dino)), contrary to [Microsoft's BEiT](https://huggingface.co/microsoft/beit-base-patch16-224-pt22k-ft22k) ([hugs's documentation](https://huggingface.co/transformers/master/model_doc/beit.html)), **yes**.
> 
> As I understood it, Mathilde **froze** the features and added a linear classification layer on top. This is visible in the way the weights for the linear classifier are shared independently from the rest of the network. This is also hinted by the good results obtained with k-NN classification.
> 
> However, if you look at other works, e.g. BEiT:
> 
>     1. the architecture is slightly different (for layer normalization) for Classification compared to Masked Image Modelling,
> 
>     2. the **whole** network is fine-tuned, so that the whole weights have to be shared again!
> 
> 
> I think it is better to see the performance of the network with frozen features, because fine-tuning hides the effect of the pre-training. I hope Mathilde keeps this approach in the future, or at least offers both perspectives, and I wish others would as well.
> 
> In a nutshell, if you want to use DINO, you can use the official implementation without worrying about a classification layer.
> 
> Or you can use hugs's implementation, and just extract the [CLS] token as your feature. I have checked [in a Github Gist](https://gist.github.com/woctezuma/a30ee1de2e5efc1a3beff8e108795374), and you should get similar results with both methods. The only thing which you have to be wary of is the pre-processing, which hugs modified, without giving a reason.

excuse me I'm back to your reply again .. what I got is, if I want to extract the features for the images before classifying it, removing the classification layer or not removing it , will not affect or change the features right ?

**Comment by fbliman** [comment]
Hi, I reopen this topic because I am a bit lost in which are the best features to extract for comparing images (looking for similar images, independet of view point)

```
def load_dino_vit_model(weights_path):
    # Load a pre-trained DINO ViT model
    # Specify the appropriate model name and path as needed
    model_name = 'vit_small_patch16_224'  # Example model name, adjust based on actual use
    model = timm.create_model(model_name, pretrained=False, num_classes=0)  # num_classes=0 for feature extraction
    checkpoint = torch.load(weights_path, map_location='cpu')
    
    # Extract the 'teacher' state dictionary and remove the 'backbone.' prefix from each key
    state_dict = checkpoint['teacher']
    adapted_state_dict = {key.replace('backbone.', ''): value for key, value in state_dict.items()}
    
    model.load_state_dict(adapted_state_dict, strict=False)

    #model = torch.hub.load('facebookresearch/dino:main', 'dino_vitb8')
    model.eval()  # Set the model to evaluation mode
    if torch.cuda.is_available():
        model.cuda()
    return model
```

I am loading this model and then just do

`output = model(image)`

this returns a 384 (or 768) dimensial feature. Is this feature the class tokens activations? or it comes from other place?

I think if this is the case it would not be ideal as in contains positional informations, which is not the best for comparing images from different viewpoints.

Also I see that from the teacher model I an not using the mlp head that is used for training and it outputs 60k+ dim for trainingand comparing to the student branch.

So, If I would like to have an image feature (with pseudo-semantinc info, nos positional) in the order of 2..3k dimansional, which would be the best place to get it from

Thanks
