### ISSUE TITLE
Difference between centering and BN

### ISSUE THREAD

**Issue by PeikeLi** [facebookresearch/dino#75]
In essence, the centering operation is like BN that calculates only the mean statistics.  Any insight into centering operation compared to BN?

**Comment by juanigp** [comment]
BN does a standarization and a transformation with learned parameters, centering does neither of these.

**Comment by mathildecaron31** [comment]
Hello @PeikeLi 

Centering is simpler than BN since we do not divide by the standard deviation and do not learn additional scaling parameters. We have tried replacing centering with BN and the performance was the same. We thus opted for the simpler option (centering).

Hope that helps
