### ISSUE TITLE
How much data is needed to train the model to a desirable point?

### ISSUE THREAD

**Issue by ouhenio** [facebookresearch/dino#77]
Since DINO was trained using Imagenet (14 million pics), I wonder how much data would be required to achieve good results under a custom dataset training scenario.

Will it work well with 100,000s of images?

**Comment by mathildecaron31** [comment]
Hi @ouhenio 

Our models are trained on ImageNet1k which contains ~1.3 million images

I cannot answer your question since I have not trained DINO on dataset of that scale.

**Comment by ouhenio** [comment]
Thanks for your response @mathildecaron31. 😊
