### ISSUE TITLE
how is segmentation achieved

### ISSUE THREAD

**Issue by AnukritiSinghh** [facebookresearch/dino#78]
Hello, thanks for providing the code. Can somebody please explain how exactly the segmentation takes place in eval_video_segmentation.py? And what is mask_neighborhood and local attention as mentioned here https://github.com/facebookresearch/dino/blob/94175993abde84179449d79e22eab7ea28dec14b/eval_video_segmentation.py#L86
Thankyou

**Comment by mathildecaron31** [comment]
Hi @AnukritiSinghh 

For video object segmentation on DAVIS we followed precisely the protocol described in this paper: https://arxiv.org/abs/2006.14613

By `mask_neighborhood` we refer to the fact of restricting the set of source nodes (context) considered for each target node, on the basis of spatial locality. Please read further detail in appendix F of https://arxiv.org/abs/2006.14613

Hope that helps
