### ISSUE TITLE
Support for training XCiT models

### ISSUE THREAD

**Issue by yadamonk** [facebookresearch/dino#79]
Could you add support or provide an example on how to train [XCiT](https://github.com/facebookresearch/xcit) models with DINO?

**Comment by mathildecaron31** [comment]
Hi @yadamonk 
Thanks for your interest!
Yes I am planning to add support for XCiT models training in a couple of weeks. I don't have much bandwidth at the moment :/

**Comment by mathildecaron31** [comment]
Done: 144f70567a6ff853b9ea44503ba37fdcf8ca41fb

**Comment by yadamonk** [comment]
Thank you so much @mathildecaron31 🤗

**Comment by mathildecaron31** [comment]
@yadamonk I realized that the `backbone only` checkpoint led to the path of the student weights... Sorry about that. I've just corrected that to that they point to the teacher weights. If you have been using the `backbone only` checkpoints please reload them.
Sorry for the inconvenience.

**Comment by yadamonk** [comment]
Thanks for the quick fix @mathildecaron31 🤗

**Comment by cyrilzakka** [comment]
Hey @mathildecaron31 sorry to reopen this again, but will the visualization and video generation code be modified to be compatible with XCiT?
