### ISSUE TITLE
Fine-tuning to other datasets using the same self-supervised paradigm

### ISSUE THREAD

**Issue by kaleidoscopical** [facebookresearch/dino#80]
Thanks for providing such an awesome repository.  

I am trying to transfer the learning ability of DINO to other datasets so that an excellent k-NN classifier can be learnt without heavy human annotations. Currently, I find the full checkpoint of `ViT-S/16` does not include information of DINO head, which  is important for fine-tuning in my experiments.

Is it possible to open-source the DINO head? Could you offer some suggestions for fine-tuning?

**Comment by juanigp** [comment]
On the paper the fine tune is done as in the DeiT paper, so you do not need the head afaik.

If you want to fine tune using DINO can't you modify the main_dino.py to preload the ViT backbone, and then use your own images instead of imagenet?

**Comment by kaleidoscopical** [comment]
I wish to fine-tune my data in a self-supervised manner, so the head is necessary.

**Comment by juanigp** [comment]
yes but you could also try to learn the head (:

**Comment by mathildecaron31** [comment]
Hi @kaleidoscopical 
The head is present in the `full checkpoint` links: https://github.com/facebookresearch/dino#pretrained-models

**Comment by Harry-KIT** [comment]
Hi @mathildecaron31. Thanks for sharing nice tips. it works well. But one problem which i am facing after whole training is evaluation. if I tried to use checkpoints to run visualize_attention.py and video_generation.py, it showed the following errors. 

RuntimeError: Error(s) in loading state_dict for VisionTransformer:
        size mismatch for pos_embed: copying a param with shape torch.Size([1, 197, 384]) from checkpoint, the shape in current 
        model is torch.Size([1, 785, 384]).
        size mismatch for patch_embed.proj.weight: copying a param with shape torch.Size([384, 3, 16, 16]) from checkpoint, the 
         shape in current model is torch.Size([384, 3, 8, 8]).
   
any suggestion is appreciated!!!
thank you~

**Comment by mons2us** [comment]
That happens when you load weights which is trained using patch size of 16, into a model using patch size of 8.
Change the argument (patch_size) of your model and things will work.

**Comment by i-aki-y** [comment]
@Harry-KIT  I think you were using a checkpoint of ViT-S/8 instead of ViT-S/16. If you want to use ViT-S/8, setting `--patch_size 8` may work.

**Comment by jaime-1998** [comment]
> Hi @kaleidoscopical The head is present in the `full ckpt` links: https://github.com/facebookresearch/dino#pretrained-models
> 
> You can start from these weights by downloading the full checkpoint and renaming it as `checkpoint.pth` into your experiment repository. For example for ViT-S/16:
> 
> step1: create experiment repo `mkdir ssl_finetuning`
> 
> step2: download full pretrained checkpoint and move it into your experiment repo `wget https://dl.fbaipublicfiles.com/dino/dino_deitsmall16_pretrain/dino_deitsmall16_pretrain_full_checkpoint.pth ssl_finetuning/checkpoint.pth`
> 
> step3: launch dino training, this will start from `checkpoint.pth` located in `output_dir` `python -m torch.distributed.launch --nproc_per_node=8 main_dino.py --arch vit_small --data_path /path/to/imagenet/train --output_dir ssl_finetuning`
> 
> Hope that helps.



> Hi @kaleidoscopical The head is present in the `full ckpt` links: https://github.com/facebookresearch/dino#pretrained-models
> 
> You can start from these weights by downloading the full checkpoint and renaming it as `checkpoint.pth` into your experiment repository. For example for ViT-S/16:
> 
> step1: create experiment repo `mkdir ssl_finetuning`
> 
> step2: download full pretrained checkpoint and move it into your experiment repo `wget https://dl.fbaipublicfiles.com/dino/dino_deitsmall16_pretrain/dino_deitsmall16_pretrain_full_checkpoint.pth ssl_finetuning/checkpoint.pth`
> 
> step3: launch dino training, this will start from `checkpoint.pth` located in `output_dir` `python -m torch.distributed.launch --nproc_per_node=8 main_dino.py --arch vit_small --data_path /path/to/imagenet/train --output_dir ssl_finetuning`
> 
> Hope that helps.

Hi @mathildecaron31,
Thanks a lot for your information, I got one question that when i finetune DINO on my own dataset, the training loss stop going down after 20 epoches (my dataset is in a specific field, not a general dataset like Imagenet1K). 
Does it means I can stop training? Or should I continue training until 100 epoches? Do you have any advice on how to early stopping the training process?
