### ISSUE TITLE
Question regarding training on pair of images

### ISSUE THREAD

**Issue by alinionutpopa** [facebookresearch/dino#83]
Hi! Awesome paper and awesome repository! Thank you for your support! I have a couple of questions I would like to address.

Would it be possible to train the model with pair of images instead of having the same image with global / local views? I mean, the images contain the same object, however, the global / local views would be on the corresponding image of student / teacher from the input pair of images.

- _**Pair -> (Image A, Image B)**_

- _**Image A -> Local View -> Student Network**_

- _**Image B -> Global View -> Teacher Network**_

 What limitations should there be in this scenario?

One example of such case is with different video frames of a moving object (e.g. a running dog) or different viewpoints of the same object (e.g. pictures of a building from different angles, or at different times of the day).

Also, the pair might have an extra label stating whether the images are similar or not. How would you adapt your head to this scenario? How would you add a loss function with regard to this new objective.

Thank you in advance!

**Comment by mathildecaron31** [comment]
Hi @alinionutpopa 

I think that this a very good remark, but as you've mentioned there is no straightforward unsupervised way to define such pairs of corresponding images. If you happen to have a dataset of video or different viewpoints of the same object then you can indeed use this information to define a positive pair.

You could also try to define a positive pair with a k-NN operation (just like in NNCLR https://arxiv.org/abs/2104.14548 for example).
