### ISSUE TITLE
Reproducing results for Image Retrieval  

### ISSUE THREAD

**Issue by yolish** [facebookresearch/dino#87]
Thank you for sharing the code for this interesting and inspiring work! 

I have tried to reproduce your results from Table 3 in the paper (Image Retrieval). However, when testing the published ViT-S/16 trained with DINO on Revisited Oxford and Paris, I have observed a gap of ~5% compared to the mAP reported in the table.

Will you be able to share the configuration and training/testing details you have used for generating the results reported in Table 3 - for both ImageNet and Google Landmarks v2? For example, the training configuration and the image size used for generating the descriptors at inference time. This can greatly help in reproducing the results.

In addition, are you planning on sharing the model trained on Google Landmarks v2?

Many thanks in advance!

**Comment by mathildecaron31** [comment]
Google Landmark DINO checkpoint is at https://dl.fbaipublicfiles.com/dino/dino_vitsmall16_googlelandmark_pretrain/dino_vitsmall16_googlelandmark_pretrain.pth

**Comment by mathildecaron31** [comment]
https://github.com/facebookresearch/dino/commit/30aedce1278129a688ccddf748f3493e2146a335

See instructions to repro here: https://github.com/facebookresearch/dino#evaluation-image-retrieval-on-revisited-oxford-and-paris
