### ISSUE TITLE
Replicating the results on Table 6 (CIFAR10)

### ISSUE THREAD

**Issue by NivC** [facebookresearch/dino#88]
Thank you very much for the interesting method and the code!

I am trying to replicate the results on Table 6 (CIFAR10) - 99.0 for top-1 accuracy.

As a starting point, I was trying to use your script _"eval_knn.py"_, but got the following error:
`Traceback (most recent call last):
  File "eval_knn.py", line 210, in <module>
    utils.init_distributed_mode(args)
  File "/cs/labs/aaa/nivc/adgym/dino/utils.py", line 469, in init_distributed_mode
    world_size=args.world_size,
AttributeError: 'Namespace' object has no attribute 'world_size'
`

Also, do you have please the configuration used to finetune the network to get the result in Table.6?

Thanks!
Niv.

**Comment by woctezuma** [comment]
Regarding the error, it arises because `world_size` was not set in:

https://github.com/facebookresearch/dino/blob/144f70567a6ff853b9ea44503ba37fdcf8ca41fb/utils.py#L445-L471

**Comment by mathildecaron31** [comment]
@woctezuma
When the job is launched on a slurm cluster with submitit the world_size is set by `run_with_submitit`:
See https://github.com/fairinternal/dino/blob/397f0053122dd784a58e3f1bfebd31d777546a2c/run_with_submitit.py#L85

@NivC 
Can you try running `python -m torch.distributed.launch --nproc_per_node=1 eval_knn.py --data_path /path/to/imagenet` for example ?
See https://github.com/fairinternal/dino#evaluation-k-nn-classification-on-imagenet

**Comment by NivC** [comment]
Thank you both!

The "https://github.com/fairinternal/dino#evaluation-k-nn-classification-on-imagenet" link seems to be broken.
Will try fixing according to your suggestions and let you know if I encounter any further problems.

Niv.

**Comment by mathildecaron31** [comment]
Ha sorry it's my bad, I had included links to the private dino repo (not public).

Please see my edited comment above. Links should work.
