### ISSUE TITLE
Bug in k-NN

### ISSUE THREAD

**Issue by igolan89** [facebookresearch/dino#89]
I think there might be a bug in the evaluation code of the k-nn classifier when computing top C and C>1 (specifically top5 in the code).
When computing the top C and C > k, the correct predictions should be narrowed to k, and not up to C.
This does not happen now, and may cause the model to be "right" on a class it gave 0 probability to.
For example, let k=1, and assume that the nearest neighbor of a test sample belong to class 0, and the ground for the tested sample is class 1. When we compute top5 for this class, we may end up thinking that the k-nn classifier was correct just because all other classes have the same score (which is 0).
A quick fix would be to just take the minimum value between k and C inside the narrow function.

**Comment by mathildecaron31** [comment]
Thanks for catching this bug :)
https://github.com/facebookresearch/dino/commit/5783b4bb552da26e8436d14be52bd1a8065ce0a0
