### ISSUE TITLE
Multi-scale feature extraction for image retrieval?

### ISSUE THREAD

**Issue by woctezuma** [facebookresearch/dino#90]
Following #72, I have noticed that there is some code for multi-scale feature extraction:
https://github.com/facebookresearch/dino/blob/ba9edd18db78a99193005ef991e04d63984b25a8/eval_knn.py#L101-L104
where three scales are used: 1, 1/sqrt(2), and 1/2.
https://github.com/facebookresearch/dino/blob/ba9edd18db78a99193005ef991e04d63984b25a8/utils.py#L795-L809

I see that this piece of code was committed for image retrieval (rather than KNN even though it appears in the code for KNN).

However, I don't see it mentioned in the paper. Does it lead to better results for image retrieval?

**Comment by mathildecaron31** [comment]
Hi @woctezuma 

We have not tried multi-scale feature extraction for k-NN. I think it is a standard practice in image retrieval though: see https://github.com/filipradenovic/cnnimageretrieval-pytorch/blob/master/cirtorch/networks/imageretrievalnet.py#L309-L324 and https://github.com/filipradenovic/cnnimageretrieval-pytorch/blob/c5368dfbbfe0286f536e374a4a35ff89578ef2e5/cirtorch/examples/test.py#L53-L55 for example.

**Comment by woctezuma** [comment]
Thank you for your answer.

To be clear, are the results shown in the paper obtained with a single scale or with multiple scales? Maybe it is mentioned in the paper, but I could not find the information with some `Ctrl+F`.

**Comment by mathildecaron31** [comment]
Paris is with multi-scale, Oxford is without.
https://github.com/facebookresearch/dino#evaluation-image-retrieval-on-revisited-oxford-and-paris

Yes it is true that I have not provided much detailed implementation details for this image retrieval benchmark in the paper but hopefully my implementation provides all the details to allow users to replicate the publishes numbers.

**Comment by woctezuma** [comment]
Thank you. I had not noticed the the information was present in the command-line examples!
