### ISSUE TITLE
How to reproduce the results of MoCoV2, BYOL, etc

### ISSUE THREAD

**Issue by Hiusam** [facebookresearch/dino#91]
Hi, I want to ask how to reproduce the results of MoCoV2, BYOL, etc in Table 2 of the paper?
What are your implementation detail, the hyperparameter settings, and training strategy?
Thank you very much!

**Comment by mathildecaron31** [comment]
Hi @Hiusam 
See https://github.com/facebookresearch/dino/issues/34

Let me know if you have any questions regarding the implementation.
