### ISSUE TITLE
Did you use ImageNet subset?

### ISSUE THREAD

**Issue by Step-Zero** [facebookresearch/dino#96]
I train dino+Vit-S with ImageNet 19k. And one epoch use 5.5 hours, and I use 8 v100 GPU. You said "Training time is 1.75 day", so if you used a subset of ImageNet?

And loss get 3.13 just after 3 epoch. log as follow

Epoch: [3/100]  [ 1320/25690]  eta: 5:30:18  loss: 3.157086 (3.156335)  lr: 0.000305 (0.000303)  wd: 0.040826 (0.040813)  time: 1.155825  data: 0.001296  max mem: 14004

**Comment by woctezuma** [comment]
#48

**Comment by mathildecaron31** [comment]
Hi @Step-Zero ,
We train on ImageNet1k train set, which consist of 1.281.167 imgs and 1000 classes (though we do not use the class information).
