### ISSUE TITLE
How much GPU memory is needed when evaluating DAVIS?

### ISSUE THREAD

**Issue by pansanity666** [facebookresearch/dino#98]
I tried 'eval_video_segmentation.py' with one 16GB V100, but CUDA out of memory always occurs when processing the 28th video, i.e. 'shooting'. 
```
RuntimeError: CUDA out of memory. Tried to allocate 8.90 GiB (GPU 0; 15.78 GiB total capacity; 3.46 GiB already allocated; 1.59 GiB free; 12.99 GiB reserved in total by PyTorch)
```

However, the length of 'shooting' is only 39, which is shorter than the previous videos. I am confused about why the out of memory happens here. 

Did you use 32GB V100 for inference?

**Comment by pansanity666** [comment]
I print the imgsize, and find that the input imgsize of 'shooting' is [3, 480, 1152], which is significantly larger than others ([3, 480, 832]),  I think this is the reason for the OOM. 
Still, did you use 32GB V100 ?

**Comment by mathildecaron31** [comment]
Hi @pansanity666 

Have you tried reducing the batch size (https://github.com/facebookresearch/dino/blob/ba9edd18db78a99193005ef991e04d63984b25a8/eval_video_segmentation.py#L264) ?

**Comment by pansanity666** [comment]
> Hi @pansanity666
> 
> Have you tried reducing the batch size (
> 
> https://github.com/facebookresearch/dino/blob/ba9edd18db78a99193005ef991e04d63984b25a8/eval_video_segmentation.py#L264
> 
> ) ?

I tried it and it doesn't work. 
In fact, the 'bs' argument is not used in the code. Only one frame (not batch) is sent to the model at a time.

**Comment by mathildecaron31** [comment]
Ha yes you're right I removed this feature when refactoring the code for simplicity. I should remove the argument to avoid confusion... Well in that case you can either 
- run code on cpu for the shooting video
- train on GPU with more memory (I used 32Gb V100 GPU)
- resize the shorter side to a smaller resolution (by changing scale_size there https://github.com/facebookresearch/dino/blob/ba9edd18db78a99193005ef991e04d63984b25a8/eval_video_segmentation.py#L224 and there https://github.com/facebookresearch/dino/blob/ba9edd18db78a99193005ef991e04d63984b25a8/eval_video_segmentation.py#L197)

**Comment by pansanity666** [comment]
> Ha yes you're right I removed this feature when refactoring the code for simplicity. I should remove the argument to avoid confusion... Well in that case you can either
> 
> * run code on cpu for the shooting video
> * train on GPU with more memory (I used 32Gb V100 GPU for 8x8 models)
> * resize the shorter side to a smaller resolution (by changing scale_size there https://github.com/facebookresearch/dino/blob/ba9edd18db78a99193005ef991e04d63984b25a8/eval_video_segmentation.py#L224
>    and there https://github.com/facebookresearch/dino/blob/ba9edd18db78a99193005ef991e04d63984b25a8/eval_video_segmentation.py#L197
>   )
> 
> What model are you using ? ViT-small 16x16 fits into memory with a 16Gb GPU in my experiments.

I am using ViT-small 8x8, and 16x16 works well in my experiments too. 
May be the torch.bmm operation leads to the OOM. 
I will try the cpu inference for shooting. 
Thank you for your suggestion and reply. 

Best,

**Comment by mathildecaron31** [comment]
Closing the issue, feel free to re-open if you have further question.
