### ISSUE TITLE
The Linear Layer weights in eval

### ISSUE THREAD

**Issue by duchenzhuang** [facebookresearch/dino#99]
Where can I get the linear layer's weights after trained by eval_linear.py. Thanks!

**Comment by mathildecaron31** [comment]
Hi, I can try to upload them shortly if that helps

**Comment by duchenzhuang** [comment]
> Hi, I can try to upload them shortly if that helps

Thank you!

**Comment by mathildecaron31** [comment]
https://github.com/facebookresearch/dino/commit/de9ee3df6cf39fac952ab558447af1fa1365362a

**Comment by mathildecaron31** [comment]
https://github.com/facebookresearch/dino/issues/117#issuecomment-926000470
https://github.com/facebookresearch/dino/commit/d2f3156bb34c32ae54312de7fe4e31580f12ff7f
